name: first

on: push

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - run: date               
    windows:
        runs-on: windows-latest
        steps:
            - run: date    
    macos:
        runs-on: macos-latest
        steps:
            - name: Print date
            - run: date   
    ubuntu_depends:
        needs: [ubuntu, windows, macos]
        runs-on: ubuntu-latest
        steps:
            - run: date   
