name: first

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
              with:
                  path: main
            - name: Step two
              run: echo "::set-output name=date::$(date + '%Y-%,-%d')"
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
              with:
                  path: main
            - name: Step two
              run: echo "::set-output name=date::$(date + '%Y-%,-%d')"
    job3:
        name: Third Job
        runs-on: macos-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
              with:
                  path: main
            - name: Step two    
              run: echo "::set-output name=date::$(date + '%Y-%,-%d')"
    job4:
        name: Fourth Job
        needs: [job1, job2, job3]
        runs-on: ubuntu-latest
        steps:
             - name: Step one
               uses: actions/checkout@v2
               with:
                   path: main
             - name: Step two   
               run: echo "::set-output name=date::$(date + '%Y-%,-%d')"    
